name: GroupManager
version: ${pluginVersion}
api: ["1.0.5"]
description: A permissions plugin
author: Luck
website: https://luckperms.net

main: me.lucko.luckperms.nukkit.LPNukkitBootstrap
load: STARTUP

commands:
  groupmanager:
    description: Manage permissions
    aliases: [gm, luckperms, lp, perm, perms, permission, permissions]
